import { ConditionalNavbar } from "@/components/ConditionalNavbar"
import { ConditionalMain } from "@/components/ConditionalMain"
import { Providers } from "@/lib/Providers"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "SICT CCS ADMIN",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-900`}
      >
        <Providers>
          <ConditionalNavbar />
          <ConditionalMain>{children}</ConditionalMain>
        </Providers>
      </body>
    </html>
  )
}
